# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: go build -o ./template-linux64 ./main.go
      - run: |
          mkdir -p /tmp/commands
          tar -zcvf /tmp/commands/template-linux64.tgz ./template-linux64

      - store_artifacts:
          path: /tmp/commands
      - persist_to_workspace:
          root: /tmp/commands
          paths:
            - template-linux64.tgz
  deploy:
    docker:
      # specify the version
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: /tmp/commands
      - run: |
          sudo apt-get update
          sudo apt-get install -y wget

          wget https://github.com/github/hub/releases/download/v2.2.9/hub-linux-amd64-2.2.9.tgz
          sudo tar -xvf hub-linux-amd64-2.2.9.tgz -C /usr/local/

          mkdir -p ~/.config/

          echo "github.com:" > ~/.config/hub
          echo "- user: srossross" >> ~/.config/hub
          echo "  oauth_token: $GITHUB_TOKEN" >> ~/.config/hub
          echo "  protocol: https" >> ~/.config/hub

          hub release create \
            -a /tmp/commands/template-linux64.tgz \
            v0.0.0-alpha.2

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
