# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: go build main.go
      - run: |
          mkdir -p /tmp/commands
          mv ./main /tmp/commands/template-linux64
      - store_artifacts:
          path: /tmp/commands
      - persist_to_workspace:
          root: /tmp/commands
          paths:
            - template-linux64
  deploy:
    docker:
      # specify the version
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: /tmp/commands
      - run: |
          sudo apt-get update
          sudo apt-get install -y wget

          wget https://github.com/github/hub/releases/download/v2.2.9/hub-linux-amd64-2.2.9.tgz
          sudo tar -xvf hub-linux-amd64-2.2.9.tgz /usr/local/

          mkdir -p ~/.config/hub/
          echo "github.com:"
          echo "- user: srossross"
          echo "  oauth_token: $GITHUB_TOKEN"
          echo "  protocol: https"

          hub release create -a ./template-linux.tgz v0.0.0-alpha.2

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
