# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run:
          name: Go Get
          command: go get -v -t -d ./... github.com/golang/lint/golint
      - run: go test -v ./...
      - run: mkdir -p /tmp/commands
      # - run: $GOPATH/bin/golint ./...
      - run:
          name: Build Linux Executable
          command: |
            GOOS=linux GOARCH=amd64
            echo ${GOOS}-${GOARCH}
            go build -o ./template-${GOOS}-${GOARCH} ./main.go
            tar -zcvf /tmp/commands/template-${GOOS}-${GOARCH}.tgz ./template-${GOOS}-${GOARCH}

      - store_artifacts:
          path: /tmp/commands
      - persist_to_workspace:
          root: /tmp/commands
          paths:
            - template-linux-amd64.tgz
  deploy:
    docker:
      # specify the version
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: /tmp/commands

      - run:
          name: Create Github Release
          command: |
            go get github.com/aktau/github-release
            ls -al /tmp/commands/
            echo Uploading to Release ${CIRCLE_TAG:-$(git describe --always)}

            github-release release \
              --user {{ORG_NAME}} \
              --repo {{REPO_NAME}} \
              --tag "${CIRCLE_TAG:-$(git describe --always)}" \
              --name "Release ${CIRCLE_TAG:-$(git describe --always)}" \
              --description "TODO: Description"

            github-release upload \
              --user {{ORG_NAME}} \
              --repo {{REPO_NAME}} \
              --tag "${CIRCLE_TAG:-$(git describe --always)}" \
              --name "template-linux-amd64.tgz" \
              --file /tmp/commands/template-linux-amd64.tgz



workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
