# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: go build main.go
      - run: |
          mkdir -p /commands
          mv ./main /commands/template-linux64
      - store_artifacts:
          path: /commands
      - persist_to_workspace:
          root: /commands
          paths:
            - template-linux64
  deploy:
    docker:
      # specify the version
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: /commands
      - run: |
          apt-get install -y wget

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
